#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CAMatchEndScreen

#include "Basic.hpp"

#include "BP_CAMatchEndScreen_classes.hpp"


namespace SDK
{

// Function BP_CAMatchEndScreen.BP_CAMatchEndScreen_C.OnRep_Object
// (BlueprintCallable, BlueprintEvent)

void ABP_CAMatchEndScreen_C::OnRep_Object()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CAMatchEndScreen_C", "OnRep_Object");

	UObject::ProcessEvent(Func, nullptr);
}

}

