#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DoorSwitch_Lockable

#include "Basic.hpp"

#include "BP_DoorSwitch_Lockable_classes.hpp"
#include "BP_DoorSwitch_Lockable_parameters.hpp"


namespace SDK
{

// Function BP_DoorSwitch_Lockable.BP_DoorSwitch_Lockable_C.ExecuteUbergraph_BP_DoorSwitch_Lockable
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DoorSwitch_Lockable_C::ExecuteUbergraph_BP_DoorSwitch_Lockable(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorSwitch_Lockable_C", "ExecuteUbergraph_BP_DoorSwitch_Lockable");

	Params::BP_DoorSwitch_Lockable_C_ExecuteUbergraph_BP_DoorSwitch_Lockable Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DoorSwitch_Lockable.BP_DoorSwitch_Lockable_C.BndEvt__BP_DoorSwitch_BP_SwitchStateMachine_K2Node_ComponentBoundEvent_0_EventEnabled__DelegateSignature
// (BlueprintEvent)

void ABP_DoorSwitch_Lockable_C::BndEvt__BP_DoorSwitch_BP_SwitchStateMachine_K2Node_ComponentBoundEvent_0_EventEnabled__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorSwitch_Lockable_C", "BndEvt__BP_DoorSwitch_BP_SwitchStateMachine_K2Node_ComponentBoundEvent_0_EventEnabled__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DoorSwitch_Lockable.BP_DoorSwitch_Lockable_C.CE_DoorUnlocked
// (BlueprintCallable, BlueprintEvent)

void ABP_DoorSwitch_Lockable_C::CE_DoorUnlocked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorSwitch_Lockable_C", "CE_DoorUnlocked");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DoorSwitch_Lockable.BP_DoorSwitch_Lockable_C.CE_DoorLocked
// (BlueprintCallable, BlueprintEvent)

void ABP_DoorSwitch_Lockable_C::CE_DoorLocked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorSwitch_Lockable_C", "CE_DoorLocked");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DoorSwitch_Lockable.BP_DoorSwitch_Lockable_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_DoorSwitch_Lockable_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorSwitch_Lockable_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DoorSwitch_Lockable.BP_DoorSwitch_Lockable_C.BndEvt__BP_SwitchStateMachine_K2Node_ComponentBoundEvent_4_EventDisabled__DelegateSignature
// (BlueprintEvent)

void ABP_DoorSwitch_Lockable_C::BndEvt__BP_SwitchStateMachine_K2Node_ComponentBoundEvent_4_EventDisabled__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorSwitch_Lockable_C", "BndEvt__BP_SwitchStateMachine_K2Node_ComponentBoundEvent_4_EventDisabled__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DoorSwitch_Lockable.BP_DoorSwitch_Lockable_C.BndEvt__BP_DoorSwitch_Lockable_BP_SwitchStateMachine_K2Node_ComponentBoundEvent_7_EventCooldownToOff__DelegateSignature
// (BlueprintEvent)

void ABP_DoorSwitch_Lockable_C::BndEvt__BP_DoorSwitch_Lockable_BP_SwitchStateMachine_K2Node_ComponentBoundEvent_7_EventCooldownToOff__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorSwitch_Lockable_C", "BndEvt__BP_DoorSwitch_Lockable_BP_SwitchStateMachine_K2Node_ComponentBoundEvent_7_EventCooldownToOff__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DoorSwitch_Lockable.BP_DoorSwitch_Lockable_C.BndEvt__BP_DoorSwitch_Lockable_BP_SwitchStateMachine_K2Node_ComponentBoundEvent_6_EventCooldownToOn__DelegateSignature
// (BlueprintEvent)

void ABP_DoorSwitch_Lockable_C::BndEvt__BP_DoorSwitch_Lockable_BP_SwitchStateMachine_K2Node_ComponentBoundEvent_6_EventCooldownToOn__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorSwitch_Lockable_C", "BndEvt__BP_DoorSwitch_Lockable_BP_SwitchStateMachine_K2Node_ComponentBoundEvent_6_EventCooldownToOn__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DoorSwitch_Lockable.BP_DoorSwitch_Lockable_C.BndEvt__BP_DoorSwitch_Lockable_BP_SwitchStateMachine_K2Node_ComponentBoundEvent_5_EventSwitchedOff__DelegateSignature
// (BlueprintEvent)

void ABP_DoorSwitch_Lockable_C::BndEvt__BP_DoorSwitch_Lockable_BP_SwitchStateMachine_K2Node_ComponentBoundEvent_5_EventSwitchedOff__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorSwitch_Lockable_C", "BndEvt__BP_DoorSwitch_Lockable_BP_SwitchStateMachine_K2Node_ComponentBoundEvent_5_EventSwitchedOff__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DoorSwitch_Lockable.BP_DoorSwitch_Lockable_C.BndEvt__BP_DoorSwitch_Lockable_BP_SwitchStateMachine_K2Node_ComponentBoundEvent_3_EventSwitchedOn__DelegateSignature
// (BlueprintEvent)

void ABP_DoorSwitch_Lockable_C::BndEvt__BP_DoorSwitch_Lockable_BP_SwitchStateMachine_K2Node_ComponentBoundEvent_3_EventSwitchedOn__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorSwitch_Lockable_C", "BndEvt__BP_DoorSwitch_Lockable_BP_SwitchStateMachine_K2Node_ComponentBoundEvent_3_EventSwitchedOn__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DoorSwitch_Lockable.BP_DoorSwitch_Lockable_C.CE_DoorEMPFinished
// (BlueprintCallable, BlueprintEvent)

void ABP_DoorSwitch_Lockable_C::CE_DoorEMPFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorSwitch_Lockable_C", "CE_DoorEMPFinished");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DoorSwitch_Lockable.BP_DoorSwitch_Lockable_C.CE_DoorEMP
// (BlueprintCallable, BlueprintEvent)

void ABP_DoorSwitch_Lockable_C::CE_DoorEMP()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorSwitch_Lockable_C", "CE_DoorEMP");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DoorSwitch_Lockable.BP_DoorSwitch_Lockable_C.Unfoamed
// (BlueprintCallable, BlueprintEvent)

void ABP_DoorSwitch_Lockable_C::Unfoamed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorSwitch_Lockable_C", "Unfoamed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DoorSwitch_Lockable.BP_DoorSwitch_Lockable_C.Foamed
// (BlueprintCallable, BlueprintEvent)

void ABP_DoorSwitch_Lockable_C::Foamed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorSwitch_Lockable_C", "Foamed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DoorSwitch_Lockable.BP_DoorSwitch_Lockable_C.CE_GameStarted
// (BlueprintCallable, BlueprintEvent)

void ABP_DoorSwitch_Lockable_C::CE_GameStarted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorSwitch_Lockable_C", "CE_GameStarted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DoorSwitch_Lockable.BP_DoorSwitch_Lockable_C.LockUnlockDoor
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ShouldLock                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class UBP_DoorStateComponent_C*         DoorActor_0                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DoorSwitch_Lockable_C::LockUnlockDoor(bool ShouldLock, class UBP_DoorStateComponent_C* DoorActor_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorSwitch_Lockable_C", "LockUnlockDoor");

	Params::BP_DoorSwitch_Lockable_C_LockUnlockDoor Parms{};

	Parms.ShouldLock = ShouldLock;
	Parms.DoorActor_0 = DoorActor_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DoorSwitch_Lockable.BP_DoorSwitch_Lockable_C.RefreshSwitchState
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_DoorSwitch_Lockable_C::RefreshSwitchState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorSwitch_Lockable_C", "RefreshSwitchState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DoorSwitch_Lockable.BP_DoorSwitch_Lockable_C.GetOwnerDoorStateMachine
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_DoorSwitch_Lockable_C::GetOwnerDoorStateMachine()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorSwitch_Lockable_C", "GetOwnerDoorStateMachine");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DoorSwitch_Lockable.BP_DoorSwitch_Lockable_C.EnableAR
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    UsedARActive                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_DoorSwitch_Lockable_C::EnableAR(bool UsedARActive)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorSwitch_Lockable_C", "EnableAR");

	Params::BP_DoorSwitch_Lockable_C_EnableAR Parms{};

	Parms.UsedARActive = UsedARActive;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DoorSwitch_Lockable.BP_DoorSwitch_Lockable_C.SwitchAR
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    DoorLockedARActive                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_DoorSwitch_Lockable_C::SwitchAR(bool DoorLockedARActive)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorSwitch_Lockable_C", "SwitchAR");

	Params::BP_DoorSwitch_Lockable_C_SwitchAR Parms{};

	Parms.DoorLockedARActive = DoorLockedARActive;

	UObject::ProcessEvent(Func, &Parms);
}

}

