#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DoNotPlayRecoveryAnimMetaData

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DoNotPlayRecoveryAnimMetaData.BP_DoNotPlayRecoveryAnimMetaData_C
// 0x0000 (0x0030 - 0x0030)
class UBP_DoNotPlayRecoveryAnimMetaData_C final : public UAnimMetaData
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_DoNotPlayRecoveryAnimMetaData_C">();
	}
	static class UBP_DoNotPlayRecoveryAnimMetaData_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_DoNotPlayRecoveryAnimMetaData_C>();
	}
};
static_assert(alignof(UBP_DoNotPlayRecoveryAnimMetaData_C) == 0x000008, "Wrong alignment on UBP_DoNotPlayRecoveryAnimMetaData_C");
static_assert(sizeof(UBP_DoNotPlayRecoveryAnimMetaData_C) == 0x000030, "Wrong size on UBP_DoNotPlayRecoveryAnimMetaData_C");

}

