#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_highlight_menuItem

#include "Basic.hpp"

#include "BP_highlight_menuItem_classes.hpp"
#include "BP_highlight_menuItem_parameters.hpp"


namespace SDK
{

// Function BP_highlight_menuItem.BP_highlight_menuItem_C.ExecuteUbergraph_BP_highlight_menuItem
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_highlight_menuItem_C::ExecuteUbergraph_BP_highlight_menuItem(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_highlight_menuItem_C", "ExecuteUbergraph_BP_highlight_menuItem");

	Params::BP_highlight_menuItem_C_ExecuteUbergraph_BP_highlight_menuItem Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_highlight_menuItem.BP_highlight_menuItem_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBP_highlight_menuItem_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_highlight_menuItem_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

