#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NavAreaDropMedium

#include "Basic.hpp"

#include "NavigationSystem_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_NavAreaDropMedium.BP_NavAreaDropMedium_C
// 0x0000 (0x0050 - 0x0050)
class UBP_NavAreaDropMedium_C final : public UNavArea
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_NavAreaDropMedium_C">();
	}
	static class UBP_NavAreaDropMedium_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_NavAreaDropMedium_C>();
	}
};
static_assert(alignof(UBP_NavAreaDropMedium_C) == 0x000008, "Wrong alignment on UBP_NavAreaDropMedium_C");
static_assert(sizeof(UBP_NavAreaDropMedium_C) == 0x000050, "Wrong size on UBP_NavAreaDropMedium_C");

}

