#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PostProcess_TeleportWarmUp

#include "Basic.hpp"

#include "BP_PostProcess_TeleportWarmUp_classes.hpp"
#include "BP_PostProcess_TeleportWarmUp_parameters.hpp"


namespace SDK
{

// Function BP_PostProcess_TeleportWarmUp.BP_PostProcess_TeleportWarmUp_C.ExecuteUbergraph_BP_PostProcess_TeleportWarmUp
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PostProcess_TeleportWarmUp_C::ExecuteUbergraph_BP_PostProcess_TeleportWarmUp(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PostProcess_TeleportWarmUp_C", "ExecuteUbergraph_BP_PostProcess_TeleportWarmUp");

	Params::BP_PostProcess_TeleportWarmUp_C_ExecuteUbergraph_BP_PostProcess_TeleportWarmUp Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PostProcess_TeleportWarmUp.BP_PostProcess_TeleportWarmUp_C.OnStop
// (BlueprintCosmetic, Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_PostProcess_TeleportWarmUp_C::OnStop()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PostProcess_TeleportWarmUp_C", "OnStop");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PostProcess_TeleportWarmUp.BP_PostProcess_TeleportWarmUp_C.OnPlay
// (BlueprintCosmetic, Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_PostProcess_TeleportWarmUp_C::OnPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PostProcess_TeleportWarmUp_C", "OnPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PostProcess_TeleportWarmUp.BP_PostProcess_TeleportWarmUp_C.Timeline_1__UpdateFunc
// (BlueprintEvent)

void ABP_PostProcess_TeleportWarmUp_C::Timeline_1__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PostProcess_TeleportWarmUp_C", "Timeline_1__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PostProcess_TeleportWarmUp.BP_PostProcess_TeleportWarmUp_C.Timeline_1__FinishedFunc
// (BlueprintEvent)

void ABP_PostProcess_TeleportWarmUp_C::Timeline_1__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PostProcess_TeleportWarmUp_C", "Timeline_1__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PostProcess_TeleportWarmUp.BP_PostProcess_TeleportWarmUp_C.Timeline_0__UpdateFunc
// (BlueprintEvent)

void ABP_PostProcess_TeleportWarmUp_C::Timeline_0__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PostProcess_TeleportWarmUp_C", "Timeline_0__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PostProcess_TeleportWarmUp.BP_PostProcess_TeleportWarmUp_C.Timeline_0__FinishedFunc
// (BlueprintEvent)

void ABP_PostProcess_TeleportWarmUp_C::Timeline_0__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PostProcess_TeleportWarmUp_C", "Timeline_0__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PostProcess_TeleportWarmUp.BP_PostProcess_TeleportWarmUp_C.IsVisible
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool ABP_PostProcess_TeleportWarmUp_C::IsVisible()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PostProcess_TeleportWarmUp_C", "IsVisible");

	Params::BP_PostProcess_TeleportWarmUp_C_IsVisible Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

