#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Projectile_Tactical

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Keaton_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Projectile_Tactical.BP_Projectile_Tactical_C
// 0x0010 (0x0540 - 0x0530)
class ABP_Projectile_Tactical_C : public ACAProjectile_Tactical
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0530(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBP_GravityStatusComponent_C*           BP_GravityStatusComponent;                         // 0x0538(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_Projectile_Tactical(int32 EntryPoint);
	void Defuse();
	void ReceiveBeginPlay();
	void BndEvt__BP_GravityStatusComponent_K2Node_ComponentBoundEvent_1_GameplayStateChanged__DelegateSignature();
	void BndEvt__BP_GravityStatusComponent_K2Node_ComponentBoundEvent_0_GameplayStateChanged__DelegateSignature();
	void SFX_Projectile_Travel_Audio_Start(const struct FCAAudioSwitchNameType& Switch_Group, const struct FCAAudioSwitchValueType& Switch_Value, const struct FCAAudioEventType& In_Flight_Audio_Event);
	void SFX_Projectile_Travel_Audio_Stop(const struct FCAAudioEventType& Stop_In_Flight_Audio_Event);
	void UpgradeGadgetToCurrentLevel();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Projectile_Tactical_C">();
	}
	static class ABP_Projectile_Tactical_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Projectile_Tactical_C>();
	}
};
static_assert(alignof(ABP_Projectile_Tactical_C) == 0x000010, "Wrong alignment on ABP_Projectile_Tactical_C");
static_assert(sizeof(ABP_Projectile_Tactical_C) == 0x000540, "Wrong size on ABP_Projectile_Tactical_C");
static_assert(offsetof(ABP_Projectile_Tactical_C, UberGraphFrame) == 0x000530, "Member 'ABP_Projectile_Tactical_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_Projectile_Tactical_C, BP_GravityStatusComponent) == 0x000538, "Member 'ABP_Projectile_Tactical_C::BP_GravityStatusComponent' has a wrong offset!");

}

