#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PostProcess_Knockback

#include "Basic.hpp"

#include "BP_PostProcess_Knockback_classes.hpp"
#include "BP_PostProcess_Knockback_parameters.hpp"


namespace SDK
{

// Function BP_PostProcess_Knockback.BP_PostProcess_Knockback_C.ExecuteUbergraph_BP_PostProcess_Knockback
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PostProcess_Knockback_C::ExecuteUbergraph_BP_PostProcess_Knockback(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PostProcess_Knockback_C", "ExecuteUbergraph_BP_PostProcess_Knockback");

	Params::BP_PostProcess_Knockback_C_ExecuteUbergraph_BP_PostProcess_Knockback Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PostProcess_Knockback.BP_PostProcess_Knockback_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_PostProcess_Knockback_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PostProcess_Knockback_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PostProcess_Knockback.BP_PostProcess_Knockback_C.OnStopOnce
// (BlueprintCosmetic, Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_PostProcess_Knockback_C::OnStopOnce()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PostProcess_Knockback_C", "OnStopOnce");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PostProcess_Knockback.BP_PostProcess_Knockback_C.OnStop
// (BlueprintCosmetic, Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_PostProcess_Knockback_C::OnStop()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PostProcess_Knockback_C", "OnStop");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PostProcess_Knockback.BP_PostProcess_Knockback_C.OnPlayOnce
// (BlueprintCosmetic, Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_PostProcess_Knockback_C::OnPlayOnce()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PostProcess_Knockback_C", "OnPlayOnce");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PostProcess_Knockback.BP_PostProcess_Knockback_C.Timeline_0__UpdateFunc
// (BlueprintEvent)

void ABP_PostProcess_Knockback_C::Timeline_0__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PostProcess_Knockback_C", "Timeline_0__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PostProcess_Knockback.BP_PostProcess_Knockback_C.Timeline_0__FinishedFunc
// (BlueprintEvent)

void ABP_PostProcess_Knockback_C::Timeline_0__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PostProcess_Knockback_C", "Timeline_0__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}

}

