#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Specialist_AudioComponent

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_CharacterNPCAudioComponent_Base_classes.hpp"
#include "Keaton_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Specialist_AudioComponent.BP_Specialist_AudioComponent_C
// 0x0008 (0x0280 - 0x0278)
class UBP_Specialist_AudioComponent_C final : public UBP_CharacterNPCAudioComponent_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_Specialist_AudioComponent_C;     // 0x0278(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_Specialist_AudioComponent(int32 EntryPoint);
	void OnDeath_New(class ACACharacter* Character, const struct FGameplayEffectSpec& Death_gameplay_effect_spec, float Damage_magnitude, const struct FNetworkedHit& Networked_hit, const class AActor* Killer);
	void ReceiveBeginPlay();
	void OnAwarenessStateChanged(ECAAwarenessState NewAwarenessState);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Specialist_AudioComponent_C">();
	}
	static class UBP_Specialist_AudioComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Specialist_AudioComponent_C>();
	}
};
static_assert(alignof(UBP_Specialist_AudioComponent_C) == 0x000008, "Wrong alignment on UBP_Specialist_AudioComponent_C");
static_assert(sizeof(UBP_Specialist_AudioComponent_C) == 0x000280, "Wrong size on UBP_Specialist_AudioComponent_C");
static_assert(offsetof(UBP_Specialist_AudioComponent_C, UberGraphFrame_BP_Specialist_AudioComponent_C) == 0x000278, "Member 'UBP_Specialist_AudioComponent_C::UberGraphFrame_BP_Specialist_AudioComponent_C' has a wrong offset!");

}

