#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Weapon_Grunt_Rocketeer

#include "Basic.hpp"

#include "BP_Weapon_Instant_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Weapon_Grunt_Rocketeer.BP_Weapon_Grunt_Rocketeer_C
// 0x0008 (0x1208 - 0x1200)
class ABP_Weapon_Grunt_Rocketeer_C final : public ABP_Weapon_Instant_Base_C
{
public:
	class USniperTurretLaserSightComponent_C*     SniperTurretLaserSightComponent2;                  // 0x1200(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Weapon_Grunt_Rocketeer_C">();
	}
	static class ABP_Weapon_Grunt_Rocketeer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Weapon_Grunt_Rocketeer_C>();
	}
};
static_assert(alignof(ABP_Weapon_Grunt_Rocketeer_C) == 0x000008, "Wrong alignment on ABP_Weapon_Grunt_Rocketeer_C");
static_assert(sizeof(ABP_Weapon_Grunt_Rocketeer_C) == 0x001208, "Wrong size on ABP_Weapon_Grunt_Rocketeer_C");
static_assert(offsetof(ABP_Weapon_Grunt_Rocketeer_C, SniperTurretLaserSightComponent2) == 0x001200, "Member 'ABP_Weapon_Grunt_Rocketeer_C::SniperTurretLaserSightComponent2' has a wrong offset!");

}

