#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPUI_ArcLens_ProjectileWidget

#include "Basic.hpp"

#include "BPUI_ArcLens_ProjectileWidget_classes.hpp"
#include "BPUI_ArcLens_ProjectileWidget_parameters.hpp"


namespace SDK
{

// Function BPUI_ArcLens_ProjectileWidget.BPUI_ArcLens_ProjectileWidget_C.ExecuteUbergraph_BPUI_ArcLens_ProjectileWidget
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPUI_ArcLens_ProjectileWidget_C::ExecuteUbergraph_BPUI_ArcLens_ProjectileWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_ArcLens_ProjectileWidget_C", "ExecuteUbergraph_BPUI_ArcLens_ProjectileWidget");

	Params::BPUI_ArcLens_ProjectileWidget_C_ExecuteUbergraph_BPUI_ArcLens_ProjectileWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPUI_ArcLens_ProjectileWidget.BPUI_ArcLens_ProjectileWidget_C.OnPlayerImpacted
// (Event, Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Impacted                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBPUI_ArcLens_ProjectileWidget_C::OnPlayerImpacted(bool Impacted)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_ArcLens_ProjectileWidget_C", "OnPlayerImpacted");

	Params::BPUI_ArcLens_ProjectileWidget_C_OnPlayerImpacted Parms{};

	Parms.Impacted = Impacted;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPUI_ArcLens_ProjectileWidget.BPUI_ArcLens_ProjectileWidget_C.OnArcLensWidgetStopUpdates
// (Event, Public, BlueprintEvent)

void UBPUI_ArcLens_ProjectileWidget_C::OnArcLensWidgetStopUpdates()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_ArcLens_ProjectileWidget_C", "OnArcLensWidgetStopUpdates");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPUI_ArcLens_ProjectileWidget.BPUI_ArcLens_ProjectileWidget_C.OnArcLensWidgetStartUpdates
// (Event, Public, BlueprintEvent)

void UBPUI_ArcLens_ProjectileWidget_C::OnArcLensWidgetStartUpdates()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_ArcLens_ProjectileWidget_C", "OnArcLensWidgetStartUpdates");

	UObject::ProcessEvent(Func, nullptr);
}

}

