#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPUI_TutorialScreen

#include "Basic.hpp"

#include "BPUI_TutorialScreen_classes.hpp"
#include "BPUI_TutorialScreen_parameters.hpp"


namespace SDK
{

// Function BPUI_TutorialScreen.BPUI_TutorialScreen_C.ExecuteUbergraph_BPUI_TutorialScreen
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPUI_TutorialScreen_C::ExecuteUbergraph_BPUI_TutorialScreen(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_TutorialScreen_C", "ExecuteUbergraph_BPUI_TutorialScreen");

	Params::BPUI_TutorialScreen_C_ExecuteUbergraph_BPUI_TutorialScreen Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPUI_TutorialScreen.BPUI_TutorialScreen_C.Back Button Selected
// (BlueprintCallable, BlueprintEvent)

void UBPUI_TutorialScreen_C::Back_Button_Selected()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_TutorialScreen_C", "Back Button Selected");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPUI_TutorialScreen.BPUI_TutorialScreen_C.BndEvt__BPUI_TutorialScreen_back_btn_K2Node_ComponentBoundEvent_0_UIElementSelected__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCABaseUIElement*                 button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPUI_TutorialScreen_C::BndEvt__BPUI_TutorialScreen_back_btn_K2Node_ComponentBoundEvent_0_UIElementSelected__DelegateSignature(class UCABaseUIElement* button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_TutorialScreen_C", "BndEvt__BPUI_TutorialScreen_back_btn_K2Node_ComponentBoundEvent_0_UIElementSelected__DelegateSignature");

	Params::BPUI_TutorialScreen_C_BndEvt__BPUI_TutorialScreen_back_btn_K2Node_ComponentBoundEvent_0_UIElementSelected__DelegateSignature Parms{};

	Parms.button = button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPUI_TutorialScreen.BPUI_TutorialScreen_C.OnHide
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UBPUI_TutorialScreen_C::OnHide()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_TutorialScreen_C", "OnHide");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPUI_TutorialScreen.BPUI_TutorialScreen_C.OnShow
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UBPUI_TutorialScreen_C::OnShow()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_TutorialScreen_C", "OnShow");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPUI_TutorialScreen.BPUI_TutorialScreen_C.OnLoaded_6AECB6764F5AC039527E919ED39554FB
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPUI_TutorialScreen_C::OnLoaded_6AECB6764F5AC039527E919ED39554FB(class UObject* Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_TutorialScreen_C", "OnLoaded_6AECB6764F5AC039527E919ED39554FB");

	Params::BPUI_TutorialScreen_C_OnLoaded_6AECB6764F5AC039527E919ED39554FB Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}

}

