#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_BR_TurretDamageResistance

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_BR_TurretDamageResistance.GE_BR_TurretDamageResistance_C
// 0x0000 (0x0930 - 0x0930)
class UGE_BR_TurretDamageResistance_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_BR_TurretDamageResistance_C">();
	}
	static class UGE_BR_TurretDamageResistance_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_BR_TurretDamageResistance_C>();
	}
};
static_assert(alignof(UGE_BR_TurretDamageResistance_C) == 0x000008, "Wrong alignment on UGE_BR_TurretDamageResistance_C");
static_assert(sizeof(UGE_BR_TurretDamageResistance_C) == 0x000930, "Wrong size on UGE_BR_TurretDamageResistance_C");

}

