#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HideWidgetMediator

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Keaton_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass HideWidgetMediator.HideWidgetMediator_C
// 0x0010 (0x0140 - 0x0130)
class UHideWidgetMediator_C final : public UCAViewMediator
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0130(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UUserWidget*                            Client;                                            // 0x0138(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_HideWidgetMediator(int32 EntryPoint);
	void SetClient(class UObject* Client_0);
	void OnExitState();
	void OnEnterState();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"HideWidgetMediator_C">();
	}
	static class UHideWidgetMediator_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHideWidgetMediator_C>();
	}
};
static_assert(alignof(UHideWidgetMediator_C) == 0x000008, "Wrong alignment on UHideWidgetMediator_C");
static_assert(sizeof(UHideWidgetMediator_C) == 0x000140, "Wrong size on UHideWidgetMediator_C");
static_assert(offsetof(UHideWidgetMediator_C, UberGraphFrame) == 0x000130, "Member 'UHideWidgetMediator_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UHideWidgetMediator_C, Client) == 0x000138, "Member 'UHideWidgetMediator_C::Client' has a wrong offset!");

}

